#% text_encoding = iso8859_1

:perform_search			:en_gb	Perform Search
:perform_search_sh		:en_gb	Perform search using entered search values
:interrupt			:en_gb	Interrupt
:interrupt_sh			:en_gb	Interrupt the current search
:clear				:en_gb	Clear
:clear_sh			:en_gb	Clear search values

:ch_attribute_name		:en_gb	Attribute Name
:ch_attribute_value		:en_gb	Attribute Value
:ch_to_indicator		:en_gb	To
:ch_attribute_value_range	:en_gb	Range

:rch_job_name			:en_gb	Job Name
:rch_design_full_name		:en_gb	Design Full Name
:rch_design_status		:en_gb	Design Status
:rch_design_owner		:en_gb	Owner
:rch_design_last_update_date	:en_gb	Design Updated

:attributes_for			:en_gb	Attributes for #1:
:to_indicator			:en_gb	to
:ext_name_mss_job_name		:en_gb	Job Name
:ext_name_mss_design_name	:en_gb	Design Name
:special_search_fields		:en_gb	Additional search criteria:
:inside_trail			:en_gb	Only include designs inside trail?
:current_user			:en_gb	Only include designs for #1?

:performing_search		:en_gb	Performing search...
:performing_search_progress	:en_gb	Found #1 records...
:performing_search_done_zero	:en_gb	No records found that match these search values.
:performing_search_done_one	:en_gb	Done - found 1 record.
:performing_search_done_many	:en_gb	Done - found #1 records.

:invalid_range			:en_gb	Invalid range for #1: #2 is greater than #3.
:no_trail			:en_gb	A trail must be placed to define the extent of the search.
:incomplete_trail		:en_gb	The trail must define a closed area for the extent of the search.
:interrupted			:en_gb	Interrupted
:no_selected_design		:en_gb	No selected design.
