#% text_encoding = iso8859_1

:single_geometry_from_map		Es muss eine einzelne Linien- oder Flächengeometrie selektiert werden.
:no_geometry_from_map			In der aktuellen Auswahl wurde kein Stützpunkt einer Geometrie in einem Datenbestand mit Schreibrecht gefunden.
:no_geometry_from_pointing		An dieser Stelle wurde kein Stützpunkt einer Geometrie in einem Datenbestand mit Schreibrecht gefunden.
:pointing_too_far_from_geom		Der Mausklick ist zu weit von der ausgewählten Linien- oder Flächengeometrie entfernt: Der zu verschiebende Stützpunkt kann nicht ermittelt werden.
