#% text_encoding = iso8859_1

:no_chain_identified			Bitte auf Liniengeometrie zeigen!
:no_chain_or_area_identified		Bitte auf Linien- oder Flächengeometrie zeigen!
:cannot_split_at_endpoint		Cannot perform a split at the endpoint of the selected chain.
:cannot_add_vertex_at_endpoint		Stützpunkt kann nicht am Ende der Liniengeometrie hizugefügt werden.
:av_transform_vertex_ptrule		Stützpunkt verschieben
:av_transform_vertex_ptrule_ht		Den hinzugefügten Stützpunkt mit der Maus verschieben.
:remove_vertex_zero_length		Stützpunkt kann nicht entfernt werden - Die Liniengeometrie hätte sonst die Länge Null.
:remove_vertex_zero_area		Stützpunkt kann nicht entfernt werden - Das Ergebnis wäre eine Linie und nicht mehr eine Fläche.
:no_intersection_on_window		Die zwei Linien schneiden sich nicht in diesem Fenster.
:line_int_chains_not_identified		Es wurden keine zwei Linien identifiziert, die geschnitten werden sollen.
:line_int_cancelled_too_far		Die Schnitt-Operation wurde abgebrochen, weil der Bestätigungs-Klick zu weit vom vorgeschlagenen Schnittpunkt entfernt ist.
