#% text_encoding = iso8859_1

:complete_ptrule_a	:en_gb	F9
:hotkey_1_a		:en_gb	F6
:hotkey_2_a		:en_gb	F7
:hotkey_3_a		:en_gb	Shift+F6
:hotkey_4_a		:en_gb	Shift+F7
:hotkey_5_a		:en_gb	Shift+F8

:applications		:en_gb	Applications
:administration		:en_gb	Administration
:mss_ptrule_gui		:en_gb	Pointing Rule Toolbox
:recent_designs		:en_gb	Recent Designs
:st_active_design	:en_gb	Update Active Design Status
