#% text_encoding = iso8859_1

:copy_map_selection			:en_gb	Copy Map Selection
:copy_map_selection_sh			:en_gb	Copy overlay design data selected in map into the active design

:map_selection_tab_label		:en_gb	Map Selection
:map_selection_header			:en_gb	Selected objects from overlay design:
:overlay_design_string			:en_gb	Overlay design: #1
:overlay_design_string_none		:en_gb	No overlay design
:select_unchanged_geometry?		:en_gb	Allow selection/display of unchanged geometry from overlay design?

:msch_count				:en_gb	Count
:msch_dataset_name			:en_gb	Dataset
:msch_external_name			:en_gb	External Name

:copying_map_selection			:en_gb	Copying map selection...
:copy_map_selection_transaction		:en_gb	Copy Overlay Map Selection

:no_map_selection			:en_gb	No objects to be copied are selected in the map window.
:not_writable				:en_gb	The #1 database is not writable.
:no_active_design			:en_gb	No active design to copy to.
:no_overlay_design			:en_gb	No overlay design to copy from.
