#% text_encoding = iso8859_1

:merge_status			:en_gb	Merging #1 #2...
:merge_complete_ok_message	:en_gb	Merge design completed.
:merge_complete_cancel_message	:en_gb	Merge design failed.
:resolving_conflicts		:en_gb	Resolving conflicts.
:post_status			:en_gb	Posting #1 #2...
:post_complete_ok_message	:en_gb	Post design completed.
:post_complete_cancel_message	:en_gb	Post design failed.

:readonly_state			:en_gb	Readonly: #1 designs are always readonly.
:readonly_auth			:en_gb	Readonly: not authorised to update this design.
:readonly_current_writer	:en_gb	Readonly: #1 has this design open.

:no_active_design		:en_gb	No active design.
:invalid_design			:en_gb	The selected design has been deleted.
:no_read_access			:en_gb	Not authorised to access design #1.
:blank_job_type			:en_gb	The job type must be entered to create a new job.
:no_state_transition_for_record	:en_gb	No state transition is available for #1 (#2 - #3).  Check your workflow configuration.

:active_design_updated		:en_gb	Design #1 has been updated.  Please commit or rollback before proceeding.
:database_updated		:en_gb	Database #1 has been updated.  Please commit or rollback before proceeding.
:conflict_dialog_active		:en_gb	The conflict dialog is active.  Close that dialog before continuing with this operation.
:conflicts_in_parent_design	:en_gb	Conflicts have been found in parent design #1.  Open that design and perform the Merge Design function before continuing with this operation.
:conflict_dialog_failure	:en_gb	The merge for design #1 did not complete, due to unresolved conflicts.
:unknown_error_during_post	:en_gb	An unexpected error has occurred while trying to post the design data.
:conflict_during_post		:en_gb	
Once you have resolved the conflicts, perform this operation 
again so that the design data can be successfully posted.
:conflicts_not_handled		:en_gb	Conflicts not handled for #1.
:auth_state_transition_error	:en_gb	You do not have sufficient authorisation to update #1 from #2 to #3.
