#% text_encoding = cp1252

:tab_label		CASE Report
:title			CASE Report

:default_soc_name	CASE dataset
:default_soc_name_tt	CASE dataset for report
:default_soc_name_sh	Select the CASE dataset to report

:ace_name		ACE Name
:ace_name_tt		The ACE Name to use
:ace_name_sh		The ACE to use for object grouping.

:user_soc_name		User SOC
:user_soc_name_tt	Select the SOC with the tables in this CASE
:user_soc_name_sh	Select the SOC with the tables in this CASE
:map_size		Map Size
:map_size_tt		Map Size
:map_size_sh		The resolution of the output map.

:template		Template
:template_tt		Report Template
:template_sh		Select the report template to use

:dump_path		Path
:dump_path_tt		Output Path
:dump_path_sh		Specify the path for output