:action		Action
:alpha		Alfabetisch
:app		App

:category	Categorie
:colon		:
:common		Common

:element_id_not_unique	Een ander dialoogelement heeft reeds 
dialog_element_id = '#1'

:filename	Bestandsnaam

:image		Image
:image_filtering	Image Filtering - Incrementeel

:module			Module

:no_app_running		Geen active applicaties

:plugin			Plugin
:plugin_action_filtering	Plugin/Action Filtering
:property		Property

:refresh_app_list		Ververs applicatie lijst

:set_image_resource	Set image source ... 
:set_large_image_resource	Set LARGE image source ...
:set_logical_values	Set 'Selector' values
:set_plugin_resource	Set plugin / action 

:value			Value

:window_id_not_unique	The window_name '#1' is not unique to this window stack.

