#% text_encoding = iso8859_1

:edit_file		Edit File
:edit_file_sht		Edit the file where this method has been defined.
:edit_file_tt		Edit File...
:export			Export data to file...
:export_sht		Select a file to which the analyzed data can be written to from a newly opened dialog.
:export_tt		Export Data to File
:help			Help
:help_sht		Provides help information about the method analyzer.
:help_tt		Help
:load_list?		Use load_list?
:load_list?_tt		Use load_list.txt File?
:load_list?_sht		Use file load_list.txt to determine which files should be read?
:print			Write data to file...
:print_sht		Select a file to which the analyzed data can be written to from a newly opened dialog.
:print_tt		Write Data to File
:quit			Quit
:quit_sht		Quits the dialog.
:quit_tt		Quit
:recursive?		Recursive?
:recursive?_tt		Visit Sub-directories?
:recursive?_sht		Look for Magik files in sub-directories?
:run_analysis		Run analysis
:run_analysis_sht	Run analysis for the selected file/directory.
:run_analysis_tt	Run Analysis
:select_path		Select file/directory/module...
:select_path_sht	Select a file, directory, or module to be analyzed from a newly opened dialog.
:select_path_tt		Select File/Directory/Module for Analysis
:stop_analysis		Cancel analysis run
:stop_analysis_sht	Cancel currently running analysis.
:stop_analysis_tt	Cancel Analysis Run

:input_selections	Input Selections
:analysis_selections	Analysis Options
:action_selections	Actions

:collecting_files	Collecting files to be processed...
:input_path		Source Code Location
:input_type		Input Type
:file			File
:directory		Directory
:known_modules		Known Modules
:module			Module
:load_list?		Use load_list?
:path_choice		...
:recursive?		Recursive?

:file_dialog_title	Select File to Analyze
:directory_dialog_title	Select Directory to Analyze


:no_progress_info	#s
:progress_info		Processing file #1 of #2 (#3%) - #5
:completed_info_1	Processing of #2 file completed.
:completed_info_n	Processing of #2 files completed.
:processing_aborted	Analysis aborted. Was processing file #1 of #2 - #5.


:gnuclient_cmd		gnuclientw -q
:gnuclient_cmd_jump	gnuclientw -q +#1
:edit_file_command	#1 "#2"