#% text_encoding = iso8859_1

:sf!method_analyzer_framework	Method Analyzer

:export			Export data to file...
:export_sht		Select a file to which the analyzed data can be written to from a newly opened dialog.
:export_tt		Export Data to File
:help			Help
:help_sht		Provides help information about the method analyzer.
:help_tt		Help
:launch_doc_file	cmd /C "#1"
:no_help_yet		Sorry, no online help available yet...
:print			Write data to file...
:print_sht		Select a file to which the analyzed data can be written to from a newly opened dialog.
:print_tt		Write Data to File
:quit			Quit
:quit_sht		Quits the dialog.
:quit_tt		Quit