#% text_encoding = iso8859_1

:analysis_options	Analysis Options

:call_analysis		Method calls
:call_analysis_tt	Method Call Analysis
:call_analysis_sht	Provides information which methods are called how often
:common_expressions	Expressions
:common_expressions_tt	Expression Analysis
:common_expressions_sht	Performs an analysis for redundant/repeated expressions
:unused_variables	Variables
:unused_variables_tt	Variable Analysis
:unused_variables_sht	Checks variable usage