#% text_encoding = iso8859_1

:run				:en_gb	Run
:run_sh				:en_gb	Run the HTTP server process
:interrupt			:en_gb	Interrupt
:interrupt_sh			:en_gb	Stop the HTTP server process
:port				:en_gb	Port
:port_sh			:en_gb	Set the listening port for the HTTP server process
:logfile_name			:en_gb	Log file
:logfile_name_sh		:en_gb	Set the name of the log file to monitor the HTTP server process
:logfile_file_selector		:en_gb	?
:logfile_file_selector_sh	:en_gb	Activate a log file selection dialog
:log_level			:en_gb	Log level (1-10)
:log_level_sh			:en_gb	Set the log level (1 - maximum; 10 - minumum)
:max_allowable_clients		:en_gb	Max clients
:max_allowable_clients_sh	:en_gb	Maximum number of concurrent connections allowed

:tab_label_services		:en_gb	Services
:tab_label_configuration	:en_gb	Configuration

:ch_directory			:en_gb	Directory
:ch_subdirectories?		:en_gb	Subdirs?
:ch_exemplar			:en_gb	Manager Class

:interrupted			:en_gb	Interrupted
:server_running_termination	:en_gb	Cannot close while the server is running.
:cannot_bind_port		:en_gb	Cannot bind port #1: another server may be on that port.
:cannot_open_logfile		:en_gb	Cannot open log file #1: dumping log to terminal.
:max_allowable_clients_exceeded	:en_gb	Maximum number of concurrent clients (#1) exceeded.
:log_level_out_of_range		:en_gb	Log level must be between 1 and 10.
:no_server_restart_command	:en_gb	No server restart command has been defined.

:unknown_status			:en_gb	(Unknown Status)
:unknown_address		:en_gb	(Unknown Address)
:log_bad_service_manager	:en_gb	Invalid service manager: #1, #2
:log_starting_server		:en_gb	Starting server
:log_restarting_server		:en_gb	Attempting to restart server process
:log_connection_stream_closed	:en_gb	Server listener stream closed
:log_error_closing_stream	:en_gb	Error closing server listener stream: #1
:log_response_sent		:en_gb	Response sent: #1
:log_skip_timed_out_request	:en_gb	Skipping timed out request
:log_connection_received	:en_gb	Connection received
:log_about_to_process		:en_gb	About to process: #1, using #2
:log_standard_server_error	:en_gb	Unexpected server error
:log_standard_user_error	:en_gb	User error (bad data or arguments)

