#% text_encoding = iso8859_1

:no_chain_identified		:en_gb	The pointing must be to a chain geometry.
:no_chain_or_area_identified	:en_gb	The pointing must be to a chain or area geometry.
:cannot_split_at_endpoint	:en_gb	Cannot perform a split at the endpoint of the selected chain.
:cannot_add_vertex_at_endpoint	:en_gb	Cannot add a vertex at the endpoint of the selected chain.
:av_transform_vertex_ptrule	:en_gb	Move vertex
:av_transform_vertex_ptrule_ht	:en_gb	Click and drag the added vertex.
:remove_vertex_zero_length	:en_gb	Cannot remove vertex - the result would be a zero-length chain.
:remove_vertex_zero_area	:en_gb	Cannot remove vertex - the result would be a line, not an area.
:no_intersection_on_window	:en_gb	The two chains do not intersect in this window.
:line_int_chains_not_identified	:en_gb	The two chains for performing the line intersection operation have not been identified.
:line_int_cancelled_too_far	:en_gb	The line intersection operation is cancelled, because the confirmation pointing is too far from the proposed intersection.
