#% text_encoding = iso8859_1

:mss_ptrule_mode		:en_gb	Toolbox Mode
:prompt_string			:en_gb	Click or drag to perform active pointing rule
:complete_ptrule		:en_gb	Complete Active Pointing Rule
:terminate_ptrule		:en_gb	Terminate Active Pointing Rule
:terminate_all_ptrules		:en_gb	Terminate All Pointing Rules

:ptrule_transaction_description	:en_gb	Toolbox: #1

:no_active_ptrule		:en_gb	No active pointing rule


