#% text_encoding = iso8859_1

:single_geometry_from_map	:en_gb	A single chain or area geometry must be selected.
:no_geometry_from_map		:en_gb	No vertex of a chain or area geometry from a writable dataset found in the current selection.
:no_geometry_from_pointing	:en_gb	No vertex of a chain or area geometry from a writable dataset found at this location.
:pointing_too_far_from_geom	:en_gb	The pointing is too far away from the selected chain or area geometry - cannot determine the vertex to move.
