#% text_encoding = iso8859_1

:run_qa				:en_gb	Run QA
:run_qa_sh			:en_gb	Run QA checks
:interrupt			:en_gb	Interrupt
:interrupt_sh			:en_gb	Interrupt QA processing
:mcn_select_all			:en_gb	Select All
:mcn_select_all_sh		:en_gb	Select all rows in check name list
:mcn_select_clear		:en_gb	Clear Selection
:mcn_select_clear_sh		:en_gb	Clear selected rows in check name list
:mcn_enable_selection		:en_gb	Enable Selected Checks
:mcn_enable_selection_sh	:en_gb	Enable selected checks in check name list
:mcn_disable_selection		:en_gb	Disable Selected Checks
:mcn_disable_selection_sh	:en_gb	Disable selected checks in check name list
:mg_select_all			:en_gb	Select All
:mg_select_all_sh		:en_gb	Select all rows in group list
:mg_select_clear		:en_gb	Clear Selection
:mg_select_clear_sh		:en_gb	Clear selected rows in group list
:mg_enable_selection		:en_gb	Enable Selected Groups
:mg_enable_selection_sh		:en_gb	Enable selected groups in group list
:mg_disable_selection		:en_gb	Disable Selected Groups
:mg_disable_selection_sh	:en_gb	Disable selected groups in group list

:tab_label_input_mode		:en_gb	Input Mode
:input_mode			:en_gb	Input mode:
:input_mode_trail		:en_gb	Within trail
:input_mode_scrapbook		:en_gb	Scrapbook
:input_mode_difference_stream	:en_gb	Changes in this alternative
:input_mode_entire_database	:en_gb	Entire database

:tab_label_managed_datasets	:en_gb	Datasets
:tab_label_managed_groups	:en_gb	Groups
:tab_label_managed_checks	:en_gb	Checks

:ch_dataset			:en_gb	Dataset
:ch_group			:en_gb	Group
:ch_check_name			:en_gb	Check Name
:ch_enabled?			:en_gb	Enabled?

:complete_status		:en_gb	Complete: #1 checks performed, #2 objects examined, #3 errors and #4 warnings found.
:interrupted			:en_gb	Interrupted
:doing_check_start		:en_gb	Performing #1...
:doing_check_progress		:en_gb	Performing #1 (#2 checked)...

:undefined_check_name		:en_gb	Undefined QA check name: #1
:no_datasets_selected		:en_gb	Select at least one dataset to be processed.
:no_checks_selected		:en_gb	Select at least one QA check to be processed.
:no_trail			:en_gb	No trail available.
:incomplete_trail		:en_gb	The trail must form an area to define the extent of the search.
:no_scrapbook_records		:en_gb	No records are currently in the scrapbook.
:dbv_at_top			:en_gb	The #1 database is at the top alternative - switch to a sub-alternative in order to check changes within an alternative.
