#% text_encoding = cp1252

:clone			Copy->
:collection_state	State
:title			Table Access
:update			Update
:select			Select
:none			None
:predicate		Predicate
:clone_tables		Copy selected attributes to:
:missing_field_copy	Skipped copy to table '#1'
Field '#2' does not exist
:proceed_with_dataset	You have selected the dataset '#1'.  Are you sure you want to copy this table access to ALL tables in this dataset?