#% text_encoding = iso8859_1

:tab_label			:en_gb	Macro Units

:refresh			:en_gb	Refresh
:edit_selected_cu_mu_relationship	:en_gb	Edit selected CU-MU relationship
:add_cus_to_mu			:en_gb	Add CUs To Macro Unit
:remove_cus_from_mu		:en_gb	Remove CUs From Macro Unit

:filter_mu_code			:en_gb	Macro unit code filter:
:default_filter_mu_code		:en_gb	<Enter Filter>
:perform_mu_filter		:en_gb	Find
:filter_cu_code			:en_gb	CU code filter:
:default_filter_cu_code		:en_gb	<Enter Filter>
:perform_all_cu_filter		:en_gb	Find

:cu_mu_list_header		:en_gb	CUs for selected macro unit:

:ch_cu_code			:en_gb	CU Code
:ch_operation			:en_gb	Operation
:ch_description			:en_gb	Description
:ch_quantity			:en_gb	Quantity
:ch_unit_multiplier		:en_gb	Multiplier

:filtering			:en_gb	Filtering...
:filter_complete		:en_gb	Filter complete: #1 CUs found.
:filter_complete_max		:en_gb	Filter complete: more than #1 CUs found (first #1 listed here).

:deleted			:en_gb	(Deleted)
:no_selected_mu			:en_gb	No selected macro unit
:no_selected_all_cus		:en_gb	No CUs selected in list of all available CUs.
:no_selected_cu_mu		:en_gb	A single entry in the list of CUs for the current macro unit must be selected.
:no_selected_cu_mus		:en_gb	No CUs selected in the list of CUs for the current macro unit.
