#% text_encoding = iso8859_1

:tab_label			:en_gb	Job Types

:refresh			:en_gb	Refresh
:edit_selected_cu_job_type	:en_gb	Edit Selected CU Job Type...
:add_cus_to_job_type		:en_gb	Add CUs To Job Type
:remove_cus_from_job_type	:en_gb	Remove CUs From Job Type

:filter_name			:en_gb	Job type name filter:
:default_filter_name		:en_gb	<Enter Filter>
:perform_job_type_filter	:en_gb	Find
:filter_cu_code			:en_gb	CU code filter:
:default_filter_cu_code		:en_gb	<Enter Filter>
:perform_all_cu_filter		:en_gb	Find

:job_type_cu_list_header	:en_gb	CUs for selected job type:

:ch_job_type_name		:en_gb	Job Type
:ch_cu_code			:en_gb	CU Code
:ch_description			:en_gb	Description

:filtering			:en_gb	Filtering...
:filter_complete		:en_gb	Filter complete: #1 CUs found.
:filter_complete_max		:en_gb	Filter complete: more than #1 CUs found (first #1 listed here).

:deleted			:en_gb	(Deleted)
:no_selected_cu_job_type	:en_gb	No selected CU job type.
:no_selected_all_cus		:en_gb	No CUs selected in list of all available CUs.
:no_selected_job_type_cus	:en_gb	No CUs selected in the list of CUs for the current job type.
