#% text_encoding = iso8859_1

:mss_cu_properties_dialog	:en_gb	CU Properties

:operation_header		:en_gb	Operations for this CU:
:excl_facility_header		:en_gb	All available facilities
:incl_facility_header		:en_gb	Facilities for this CU and operation:
:attribute_header		:en_gb	Attributes for this facility/CU/operation:
:add_incl_facility		:en_gb	Add
:remove_incl_facility		:en_gb	Remove

:ch_enabled?			:en_gb	Enabled?
:ch_operation			:en_gb	Operation
:ch_material_cost		:en_gb	Material Cost
:ch_labor_cost			:en_gb	Labor Cost
:ch_partition_name		:en_gb	Partition
:ch_table_name			:en_gb	Table
:ch_attribute_name		:en_gb	Attribute Name
:ch_attribute_value		:en_gb	Attribute Value

:current_object_desc_none	:en_gb	No current CU.
:current_object_desc		:en_gb	Current CU: #1 - #2
:transaction_apply		:en_gb	Update CU Properties

:prompt_save_changes		:en_gb	Do you want to save the changes you made to '#1'?
:not_writable			:en_gb	The configuration database is not writable.
:max_attribute_length_exceeded	:en_gb	Maximum attribute length of #1 exceeded.
