#% text_encoding = iso8859_1

:tab_label			:en_gb	Cost Groups

:refresh			:en_gb	Refresh
:edit_selected_cu_cost_group	:en_gb	Edit Selected CU Cost Group
:edit_selected_cu_cost_group_item	:en_gb	Edit Selected CU Cost Group Item

:current_cu_cost_group		:en_gb	Cost group:
:filter_cu_code			:en_gb	CU code filter:
:filter_description		:en_gb	Description filter:
:default_filter_cu_code		:en_gb	<Enter Filter>
:perform_filter			:en_gb	Find

:ch_cu_code			:en_gb	CU Code
:ch_operation			:en_gb	Operation
:ch_description			:en_gb	Description
:ch_material_cost		:en_gb	Mat'l U.C.
:ch_labor_cost			:en_gb	Labor U.C.

:filtering			:en_gb	Filtering...
:filter_complete		:en_gb	Filter complete: #1 CUs found.
:filter_complete_max		:en_gb	Filter complete: more than #1 CUs found (first #1 listed here).

:no_current_cu_cost_group	:en_gb	A cost group must be selected.
:no_selected_cu_list		:en_gb	An entry in the CU list must be selected.
