#% text_encoding = iso8859_1

:tab_label			:en_gb	CU Properties

:refresh			:en_gb	Refresh
:edit_selected_cu_definition	:en_gb	Edit Selected CU Definition...
:edit_selected_cu_properties	:en_gb	Edit Properties For Selected CU...
:clone_selected_cu_definition	:en_gb	Clone Selected CU Definition

:filter_cu_code			:en_gb	CU code filter:
:filter_description		:en_gb	Description filter:
:default_filter_cu_code		:en_gb	<Enter Filter>
:perform_filter			:en_gb	Find

:ch_cu_code			:en_gb	CU Code
:ch_description			:en_gb	Description

:filtering			:en_gb	Filtering...
:filter_complete		:en_gb	Filter complete: #1 CUs found.
:filter_complete_max		:en_gb	Filter complete: more than #1 CUs found (first #1 listed here).

:deleted			:en_gb	(Deleted)
:no_selected_cu_definition	:en_gb	No selected CU definition.
