#% text_encoding = iso8859_1

:tab_label			:en_gb	Import/Export

:refresh			:en_gb	Refresh
:import_cu_definitions		:en_gb	Import CU Definitions...
:export_cu_definitions		:en_gb	Export CU Definitions...

:export_mode_cus?		:en_gb	CU export mode:
:filter_cu_code			:en_gb	CU code filter:
:filter_description		:en_gb	Description filter:
:default_filter_cu_code		:en_gb	
:export_cus?			:en_gb	Export CU definitions?
:export_cu_operations?		:en_gb	Export CU operation definitions?
:export_cu_facilities?		:en_gb	Export CU facility relationships?
:export_cu_groups?		:en_gb	Export CU groups?
:export_cu_job_types?		:en_gb	Export CU job types?
:export_cu_mus?			:en_gb	Export CU macro unit definitions?
:cg_export_override_only?	:en_gb	Export cost group overrides only?
:import_dialog_title		:en_gb	Import CU Definitions
:export_dialog_title		:en_gb	Export CU Definitions

:export_mode_cost_groups?	:en_gb	Cost group export mode:
:current_cu_cost_group		:en_gb	Select cost group:

:import_progress		:en_gb	Imported #1 lines...
:import_complete		:en_gb	Import complete: #1 lines read, #2 errors found.
:imp_max_errors_exceeded	:en_gb	Maximum of #1 errors encountered - stopping import.
:imp_no_header			:en_gb	Header indicator CU_EXPORT not found.
:imp_wrong_version		:en_gb	Wrong version - expected a value from #1 to #2, actual value is #3.
:imp_unknown_key		:en_gb	Unknown import key: #1.
:imp_unknown_date_format	:en_gb	Cannot convert #1 to a date value.
:imp_no_cu_entered		:en_gb	CU code cannot be blank.
:imp_no_matching_cu		:en_gb	No CU named #1.
:imp_multiple_matching_cus	:en_gb	Multiple (#2) CUs named #1.
:imp_no_operation_entered	:en_gb	Operation code cannot be blank.
:imp_fac_no_partition_and_table	:en_gb	Unknown partition and table combination: #1, #2.
:imp_no_matching_operation	:en_gb	No CU operation named #1, #2.
:imp_fac_def_no_target_table	:en_gb	No target table for facility definition - check mss_cu_facility_definition configuration.
:imp_fac_no_attr_key		:en_gb	Expected ATTR keyword, but received #1.
:imp_fac_no_attr_name		:en_gb	Attribute #1 is not defined for facility definition #2, #3.
:imp_fac_no_match_attr_value	:en_gb	Invalid value #2 for attribute #1.
:imp_no_cu_group_entered	:en_gb	CU group cannot be blank.
:imp_no_matching_cu_group	:en_gb	No CU group named #1.
:imp_no_current_cu_group	:en_gb	No current CU group - cannot process #1.
:imp_no_cu_job_type_entered	:en_gb	CU job type cannot be blank.
:imp_no_matching_cu_job_type	:en_gb	No CU job type named #1.
:imp_no_current_cu_job_type	:en_gb	No current CU job type - cannot process #1.
:imp_not_macro_unit		:en_gb	The usage for CU #1 must be Macro Unit to add MU relationships.
:imp_no_current_cu_mu		:en_gb	No current CU macro unit - cannot process #1.
:imp_no_cu_cost_group_entered	:en_gb	Cost group cannot be blank.
:imp_no_matching_cu_cost_group	:en_gb	No cost group named #1.
:imp_no_current_cu_cost_group	:en_gb	No current cost group - cannot process #1.

:export_gathering_cus		:en_gb	Gathering CU definitions for export...
:export_cus_progress		:en_gb	Exported #1 of #2 CU definitions...
:export_gathering_cu_ops	:en_gb	Gathering CU operation definitions for export...
:export_cu_ops_progress		:en_gb	Exported #1 of #2 CU operation definitions...
:export_gathering_cu_facs	:en_gb	Gathering CU facility relationships for export...
:export_cu_facs_progress	:en_gb	Exported #1 of #2 CU facility relationships...
:export_gathering_cu_groups	:en_gb	Gathering CU groups for export...
:export_cu_groups_progress	:en_gb	Exported #1 of #2 CU groups...
:export_gathering_cu_job_types	:en_gb	Gathering CU job types for export...
:export_cu_job_types_progress	:en_gb	Exported #1 of #2 CU job types...
:export_cus_done		:en_gb	Export complete: #1 records processed.
:export_gathering_cu_mus	:en_gb	Gathering CU macro units for export...
:export_cu_mus_progress		:en_gb	Exported #1 of #2 CU macro unit definitions...

:export_cu_cost_group_progress	:en_gb	Exporting CU cost group #1...
:export_cu_cost_group_done	:en_gb	Export of CU cost group information complete.

:csv_filter			:en_gb	CSV files (*.csv)
:csv_filetype			:en_gb	.csv

:no_cus_for_export		:en_gb	No CUs have been selected for export.
:no_cu_cost_group_for_export	:en_gb	No CU cost group has been selected for export.
:no_export_mode_selected	:en_gb	No export mode selected.
:view_not_writable		:en_gb	The CU configuration database is not writable.
:file_not_readable		:en_gb	File #1 cannot be read.
:file_not_writable		:en_gb	File #1 cannot be created.
