#% text_encoding = iso8859_1

:tab_label			:en_gb	CU Groups

:refresh			:en_gb	Refresh
:edit_selected_cu_group_definition	:en_gb	Edit Selected CU Group...
:add_cus_to_group		:en_gb	Add CUs To Group
:remove_cus_from_group		:en_gb	Remove CUs From Group

:filter_name			:en_gb	Group name filter:
:default_filter_name		:en_gb	<Enter Filter>
:perform_group_filter		:en_gb	Find
:filter_cu_code			:en_gb	CU code filter:
:default_filter_cu_code		:en_gb	<Enter Filter>
:perform_all_cu_filter		:en_gb	Find

:group_cu_list_header		:en_gb	CUs for selected group:

:ch_group_name			:en_gb	Group
:ch_cu_code			:en_gb	CU Code
:ch_description			:en_gb	Description

:filtering			:en_gb	Filtering...
:filter_complete		:en_gb	Filter complete: #1 CUs found.
:filter_complete_max		:en_gb	Filter complete: more than #1 CUs found (first #1 listed here).

:deleted			:en_gb	(Deleted)
:no_selected_cu_group		:en_gb	No selected CU group.
:no_selected_all_cus		:en_gb	No CUs selected in list of all available CUs.
:no_selected_group_cus		:en_gb	No CUs selected in the list of CUs for the current group.
