#% text_encoding = iso8859_1

:undo_a				:en_gb	Ctrl+Z
:redo_a				:en_gb	Ctrl+Y
:cut_a				:en_gb	Ctrl+X
:copy_a				:en_gb	Ctrl+C
:paste_a			:en_gb	Ctrl+V
:refresh_a			:en_gb	F5

:tools				:en_gb	Tools

:cut				:en_gb	Cut
:copy				:en_gb	Copy
:paste				:en_gb	Paste
:refresh			:en_gb	Refresh
:activate_pointing_rule_editor	:en_gb	Edit Pointing Rule Definitions...
:edit_pointing_rule		:en_gb	Edit Selected Pointing Rule Definition...
:clone_pointing_rule		:en_gb	Clone Selected Pointing Rule Definition
:import_pointing_rules		:en_gb	Import Pointing Rule Definitions...
