#% text_encoding = iso8859_1

:goto_object			:en_gb	Goto Objects
:goto_object_sh			:en_gb	Goto the selected object(s)
:highlight_object		:en_gb	Highlight Objects
:highlight_object_sh		:en_gb	Highlight the selected object(s)
:select_object			:en_gb	Select Objects
:select_object_sh		:en_gb	Selects the selected object(s) in the current map
:edit_object			:en_gb	Edit Object
:edit_object_sh			:en_gb	Edit the selected object
:copy_to_scrapbook		:en_gb	Copy to Scrapbook
:copy_to_scrapbook_sh		:en_gb	Copy the selected objects to the scrapbook
:auto_fix			:en_gb	Auto-Fix
:auto_fix_sh			:en_gb	Automatically fix selected errors, when possible
:export_to_excel		:en_gb	Export to Excel
:export_to_excel_sh		:en_gb	Export the current set of QA results to Excel
:display_first_result_page	:en_gb	First Page
:display_first_result_page_sh	:en_gb	Display the first page of QA results
:display_prev_result_page	:en_gb	Previous Page
:display_prev_result_page_sh	:en_gb	Display the previous page of QA results
:display_next_result_page	:en_gb	Next Page
:display_next_result_page_sh	:en_gb	Display the next page of QA results
:display_last_result_page	:en_gb	Last Page
:display_last_result_page_sh	:en_gb	Display the last page of QA results

:rch_table_name			:en_gb	Table Name
:rch_x_coordinate		:en_gb	X
:rch_y_coordinate		:en_gb	Y
:rch_description		:en_gb	Description
:rch_auto_fix_available		:en_gb	Auto Fix?

:tab_label			:en_gb	Error List

:auto_fix_pending		:en_gb	Pending
:auto_fix_ok			:en_gb	OK
:auto_fix_failed		:en_gb	Failed
:auto_fix_transaction		:en_gb	QA Auto Fix
:displaying_page		:en_gb	Displaying page #1 of #2.
:updating_result_list		:en_gb	Updating results...
:updating_result_list_progress	:en_gb	Updating results (#1 so far)...
:performing_auto_fix		:en_gb	Performing auto-fix...
:auto_fix_performed		:en_gb	Auto-fix performed (#1 objects examined, #2 objects fixed).
:qa_scrapbook			:en_gb	QA Scrapbook
:copied_to_scrapbook		:en_gb	#1 objects copied to scrapbook.
:exporting_to_excel		:en_gb	Exporting to Excel...
:excel_sheet_name		:en_gb	QA Report

:maximum_error_count_exceeded	:en_gb	More than #1 errors reported.  Only the first #1 displayed here.

:no_selected_record		:en_gb	No selected record.
:no_selected_records		:en_gb	No selected records.
:no_bounds_for_goto		:en_gb	The selected objects do not have geometry in the map currently displayed in the main view.  To goto a different map, select a single record and perform the goto on that record, which will cause the main view to display the world for that record.
:no_auto_fix_pending_selected	:en_gb	No records selected where the Auto Fix status is pending.
:no_auto_fix_datasets_selected	:en_gb	The selected records cannot have Auto Fix processing done.  Possibly, they have been fixed already.
:cannot_start_excel		:en_gb	Cannot start Microsoft Excel.  Please verify that it is installed on this computer.
:excel_could_not_get_access	:en_gb
Cannot get access to Microsoft Excel since it is currently busy.
Please close any windows that are currently open in Microsoft Excel.
