:action	Aktion

:alpha		Alphabetisch
:app	Applikation
:category	Kategory
:colon			:
:common		Normal

:element_id_not_unique	Ein anderes Dialogelement hat schon 
dialog_element_id = '#1'
:filename		Dateiname
:image			Bild
:image_filtering	Bild filtern - inkrementell

:module			Modul	
:no_app_running		Keine aktive Applikation
:plugin	Plugin
:plugin_action_filtering	Plugin / Aktion filtern
:product			Produkt
:property	Eigenschaft
:refresh_app_list		Applikationsliste erneuern

:set_image_resource	Bild ausw‰hlen ... 

:set_large_image_resource	Groﬂes Icon w‰hlen ...
:set_logical_values	Auswahlwerte festlegen
:set_plugin_resource	Setze Plugin / Aktion 
:value		Wert

:window_id_not_unique	window_name '#1' ist mehrmals vorhanden.

