#% text_encoding = iso8859_1

:caption			:en_gb	MSS map trail extensions

:note_extend_parallel		:en_gb
Use the extend discrete spacing parameter to control the trail length while
dragging the mouse in Extend Parallel mode:
- Hold the Ctrl key to snap the segment length to a multiple of this value.
- Hold the Shift key to snap the total length to a multiple of this value.
Use the offset discrete spacing parameter to control to trail offset
distance while dragging the mouse in Offset Parallel mode:
- Hold the Ctrl key to snap the offset distance to a multiple of this value.

:discrete_spacing_label		:en_gb	Extend discrete spacing:
:offset_discrete_spacing_label	:en_gb	Offset discrete spacing:
:corner_style_label		:en_gb	Corner style:
:cs_circular			:en_gb	Round
:cs_square			:en_gb	Square
:cs_bevelled			:en_gb	Bevelled
:cs_acute			:en_gb	Acute
