#% text_encoding = iso8859_1

:extend_parallel	:en_gb	Extend Parallel by Dragging
:extend_parallel_prompt	:en_gb	Click or drag to extend trail parallel to selection
:offset_parallel	:en_gb	Offset Parallel by Dragging
:offset_parallel_prompt	:en_gb	Click or drag to offset trail parallel to its current position

:total_length		:en_gb	Tot: #1
:segment_length		:en_gb	Seg: #1

:no_current_trail	:en_gb	No current trail point to initiate parallel from.
:no_current_selection	:en_gb	The selected geometries must be one or more chains or areas that form a continuous route.
:not_continuous		:en_gb	The selected geometries do not form a continuous route.
:cannot_get_offset_sectors	:en_gb
Cannot determine offset sectors.  This may happen if the geometries that are selected result in loops, or double back on themselves.
