#% text_encoding = iso8859_1

:insert_task			:en_gb	Insert Task...
:insert_task_sh			:en_gb	Insert a new scheduled task
:update_selected_task		:en_gb	Update Selected Task...
:update_selected_task_sh	:en_gb  Update the selected task
:delete_selected_task		:en_gb	Delete Selected Task
:delete_selected_task_sh	:en_gb  Delete the selected task
:refresh_result_list		:en_gb	Refresh
:refresh_result_list_sh		:en_gb	Refresh list of scheduled tasks

:rch_type			:en_gb	Type
:rch_scheduled_start_time	:en_gb	Start Time
:rch_submitter			:en_gb	Submitter
:rch_priority			:en_gb	Priority
:rch_schedule_interval		:en_gb	Interval

:tab_label			:en_gb	Scheduled Tasks
:search_time_interval		:en_gb	List tasks scheduled within the next:
:once				:en_gb	Once

:confirm_delete			:en_gb	Delete task #1?
:no_selected_task		:en_gb	No selected task.
