#% text_encoding = iso8859_1

:ch_cu_code			:en_gb	CU Code
:ch_description			:en_gb	Description
:ch_sh_operation		:en_gb	Oper.
:ch_sh_work_point_number	:en_gb	Work Pt.
:ch_sh_quantity			:en_gb	Qty.
:ch_sh_unit_multiplier		:en_gb	Mult.
:ch_sh_valid_for_record?	:en_gb	OK
:ch_report_work_point_number	:en_gb	Work Pt.
:ch_operation			:en_gb	Operation
:ch_work_point_number		:en_gb	Work Pt.
:ch_quantity			:en_gb	Quantity
:ch_unit_multiplier		:en_gb	Multiplier
:ch_material_unit_cost		:en_gb	Mat'l U.C.
:ch_labor_unit_cost		:en_gb	Labor U.C.
:ch_total_unit_cost		:en_gb	Unit Cost
:ch_dimensionality		:en_gb	U.C. Type
:ch_combined_quantity		:en_gb	Net Qty
:ch_material_total_cost		:en_gb	Material Cost
:ch_labor_total_cost		:en_gb	Labor Cost
:ch_total_cost			:en_gb	Total Cost

:as_display_tree_arg_not_self	:en_gb	The argument for converting this CU holder to a display tree refers to a different CU holder record.
