#% text_encoding = iso8859_1

:panel_header			:en_gb	Compatible units for current object:
:insert_cu			:en_gb	Insert
:update_cu			:en_gb	Update
:delete_cu			:en_gb	Delete

:default_operation		:en_gb	Install
:cu_code			:en_gb	CU
:work_point_number		:en_gb	WP
:quantity			:en_gb	Qty
:unit_multiplier		:en_gb	Mult

:undefined_cu			:en_gb	Undefined CU: #1
:undefined_cu_and_operation	:en_gb	Undefined CU and operation: #1, #2
:no_selected_cu			:en_gb	No CU selected.
:cannot_update_to_macro_unit	:en_gb	CU #1 is a macro unit.  Existing CUs cannot be updated to become a macro unit - instead, delete the old CU and insert a new macro unit.
:mu_config_no_children		:en_gb	CU #1 is a macro unit, but it does not have any child units.  Contact your system administrator to correct this configuration error.
