#% text_encoding = iso8859_1

:panel_header			:en_gb	Enter options to query for new compatible units:
:perform_filter			:en_gb	Filter

:default_operation		:en_gb	Install
:query_operation		:en_gb	Operation
:query_cu_code			:en_gb	CU code
:query_description		:en_gb	Description
:query_use_job_type?		:en_gb	Limit results to active job type?
:query_group			:en_gb	By group
:query_facility			:en_gb	By facility
:query_max			:en_gb	Max to display
:query_results			:en_gb	Results of the compatible units query:

:ch_enabled?			:en_gb	Enabled?
:ch_attribute_name		:en_gb	Attribute Name
:ch_attribute_value		:en_gb	Attribute Value
:ch_cu_code			:en_gb	CU Code
:ch_operation			:en_gb	Operation
:ch_description			:en_gb	Description

:invalid_group			:en_gb	Select a group to perform this query.
:invalid_facility		:en_gb	Select a facility to perform this query.
