#% text_encoding = iso8859_1

:alternative_up		Go To Parent Alternative
:alternative_up_tt	Go To Parent Alternative
:alternative_up_sh	Go to the parent alternative
:choose_database	Database...
:choose_database_tt	Choose Database
:choose_database_sh	Select a database from a list...
:commit			Commit Changes
:commit_tt		Commit Changes
:commit_sh		Commit all unsaved changes
:database_expression	Database:
:database_info		Database View Information...
:database_info_tt	Database View Information
:database_info_sh	Provides detail information about the database view
:rollback		Rollback Changes
:rollback_tt		Rollback Changes
:rollback_sh		Discard all unsaved changes
:rollforward		Rollforward
:rollforward_tt		Rollforward
:rollforward_sh		Synchronize the view with the database
:select_alternative	Select a Subalternative...
:select_alternative_tt	Select a Subalternative
:select_alternative_sh	Select a subalternative from a list
:toggle_access_mode	Toggle Access Mode
:toggle_access_mode_tt	Toggle Access Mode
:toggle_access_mode_sh	Change the access mode to the database

:default_view_name	{#2}
:file_header		File
:file_path_col_sep	#s|#s
:no_alternative_info	?
:no_data_available	- no data available -
:searchpath_header	Searchpath

:|message|		Message DB
:|Ace (Replica)|	ACE Top View
:|Auth|			Authorization

:alternative_heading	Alternative
:application		Application
:changed?_heading	Updated?
:class_heading		Magik Class
:database_type_heading	DB Type
:db_type_string_heading	DB Type
:dbc_title		Select A Database
:ext_name_heading	External Name
:external		External
:files_heading		Database Files
:int_tables_heading	Int. Tables
:internal		Internal
:mode_heading		Access
:name_heading		Internal Name
:system			System
:tables_heading		Tables
:user_tables_heading	User Tables
:ds_wrong_inheritance	The provide value must refer to a dataset object that inherits from from sw_dataset_mixin.

:ac_title		Select Alternative
:dbi_title		Database Information - #1

:db_common_info_msg
Database ext. name: #1
         int. name: #2
Database Class    : #3
Magik Object      : #4
User/int. Tables  : #5 / #6
Alternative Path  : #7
Access Mode       : #8
Uncommitted Data? : #9