#% text_encoding = iso8859_1

:tab_label			Records
:table_info			Table: #2 [#1] - Records: #3
:edit_object			Edit Record
:edit_object_sh			Edit Record in Embedded Editor
:edit_object_tt			Edit current record in embedded editor
:edit_object_floating		Edit Record...
:edit_object_floating_sh	Edit Record in Floating Editor
:edit_object_floating_tt	Edit current record in floating editor
:first				Goto First Record Set
:first_tt			Goto First Record Set
:first_sh			Goto first record set
:get				Get Record Set
:get_tt				Get Record Set
:get_sh				Get record set
:last				Goto First Record Set
:last_tt			Goto Last Record Set
:last_sh			Goto last record set
:previous_one			Show Previous Record Set
:previous_one_tt		Show Previous Record Set
:previous_one_sh		Show previous record set
:next_one			Show Next Record Set
:next_one_tt			Show Next Record Set
:next_one_sh			Show next record set
:no_set_pos_info		Record navigation not supported
:set_pos_info			Set: #1 of #2 - Records #3..#4
