#% text_encoding = iso8859_1

:tab_label			Tables

:size_heading			Records
:type_heading			#s
:int_name_heading		Internal Name
:ext_name_heading		External Name

:edit_object			Editor for Table
:edit_object_tt			Launch Embedded Editor for Table
:edit_object_sh			Edit current table in embedded editor
:edit_object_floating		Editor for Table...
:edit_object_floating_tt	Launch Floating Editor for Table
:edit_object_floating_sh	Edit current table in floating editor
:empty_tables?			Empty Tables?
:empty_tables?_sh		Display empty tables?
:empty_tables?_tt		Show Empty Tables?
:list				Show Table Records
:list_sh			Display table records
:list_tt			Show Table Records
:refresh			Refresh
:refresh_sh			Refresh table list
:refresh_tt			Refresh Table List			
:system_tables?			System Tables?
:system_tables?_sh		Display system tables?
:system_tables?_tt		Show System Tables?
:table_size?			Table Size?
:table_size?_sh			Display table size?
:table_size?_tt			Show Table Size?

:describe_fields		Describe Table Fields
:describe_triggers		Describe Table Triggers
:describe_phys_fields		Describe Physical Fields
:derived_fields			List Derived Fields
:geometry_fields		List Geometry Fields
:join_fields			List Join Fields
:key_fields			List Key Fields
:physical_fields		List Physical Fields

:dd_info_frame_title		[#1]#2 - #3