#% text_encoding = iso8859_1

:database			Database
:disable_authorization		Disable Authorization
:display			Display
:edit_object			Edit Object...
:edit_object_floating		Edit Object...
:edit_object_floating_sh	Edit Object in Floating Editor
:edit_object_floating_tt	Edit current object in floating editor
:edit_object_sh			Edit Object in Embedded Editor
:edit_object_tt			Edit current object in embedded editor
:export_completed_info		Data has been written to file:#n#1.
:export_directory		Export Directory...
:export_directory_sh		Select directory for HTML export files
:export_directory_tt		Directory for HTML Export Files
:export_to_html			Create HTML file for list data
:export_to_html_sh		Create an HTML file for the displayed list data
:export_to_html_tt		Create HTML File for List Data
:file				File
:restore_authorization		Restore Authorization
:sel_exp_dir			Export Directory
:suspend			Close
:table				Table
:table_tab_label		Tables
:title				Table Inspector
:title_with_view_info		Table Inspector - Dataset '#1'