#% text_encoding = iso8859_1

:all_fields				All Fields
:apply_field_display_options		Apply Field Display Options
:apply_field_display_options_sh		Apply field display options
:apply_field_display_options_tt		Apply Field Display Options
:clear_databus_events_sh		Clear databus event toggle settings
:clear_databus_events_tt		Clear Databus Event Toggles
:clear_field_disp_options_sh		Clear all field display option widgets
:clear_field_disp_options_tt		Clear Field Display Options
:databus_event_name			:#1
:dd_derived_field			Derived
:dd_geom_field				Geometry
:dd_join_field				Join
:dd_phys_field				Physical
:disp_field_types			Display Fields:
:editor_data_options			Editor - Field Collection Options
:editor_databus_events			Editor - Databus Event Processing
:editor_display_options			Editor - Field Display Options
:field_name_filter			Field Name Filter:
:internal_field				Internal
:set_default_databus_events_sh		Set defaults for databus event processing
:set_default_databus_events_tt		Set Default Databus Events
:set_default_field_disp_options_sh	Set defaults for field fisplay options widgets
:set_default_field_disp_options_tt	Set Default Field Display Options
:tab_label				Options
:visible_fields				Visible Fields
:record_data_options			Records - Display Options
:record_list_size			Number of Records in the List: 