#% text_encoding = iso8859_1

:mss_ptrule_options_menu	:en_gb	Toolbox Options
:close				:en_gb	Close

:placement_mode_tab_label	:en_gb	Placement
:placement_mode			:en_gb	Placement mode:
:pm_design			:en_gb	Design
:pm_data_maintenance		:en_gb	Data Maintenance

:offset_tab_label		:en_gb	Offset
:offset_distance		:en_gb	Offset distance:
:offset_direction		:en_gb	Offset direction:
:offset_direction_left		:en_gb	Left
:offset_direction_right		:en_gb	Right

:move_tab_label			:en_gb	Move
:move_disconnect_before_transform?	:en_gb	Disconnect before performing move vertex?
