#% text_encoding = iso8859_1

:refresh			:en_gb	Refresh Pointing Rule List
:activate_options_dialog	:en_gb	Options...

:missing_root_folder		:en_gb	No root folder has been configured to display available pointing rules.
:no_ptrule_manager		:en_gb	No pointing rule manager has been configured for this activity.

:no_active_pointing_rule	:en_gb	No active pointing rule
:active_pointing_rule		:en_gb	Active pointing rule: #1
:no_match_by_name		:en_gb	No entry found matching "#1"
