#% text_encoding = iso8859_1

:title_job_and_design		:en_gb	New Job and Design
:title_job			:en_gb	New Job
:title_design			:en_gb	New Top-Level Design for #1
:title_sub_design		:en_gb	New Sub-Design for #1

:ch_attribute_name		:en_gb	Attribute Name
:ch_attribute_value		:en_gb	Attribute Value

:ext_name_mss_job_name		:en_gb	Job Name
:ext_name_mss_design_name	:en_gb	Design Name
:ext_name_mss_job_comments	:en_gb	Job Comments
:ext_name_mss_design_comments	:en_gb	Design Comments

:mode_job			:en_gb	job
:mode_job_and_design		:en_gb	job and design
:mode_design			:en_gb	design
:mode_sub_design		:en_gb	sub-design

:mandatory_attribute		:en_gb	A value for #1 must be entered.
:no_trail			:en_gb	A trail must be placed to define the extent of the design.
:incomplete_trail		:en_gb	The trail must define a closed area for the extent of the design.
:creating_data			:en_gb	Creating #1...
