#% text_encoding = iso8859_1

:new_job_and_design		:en_gb	New Job and Design...
:new_job_and_design_sh		:en_gb	Create a new job and design
:new_job			:en_gb	New Job...
:new_job_sh			:en_gb	Create a new job
:new_top_level_design		:en_gb	New Top-Level Design...
:new_top_level_design_sh	:en_gb	Create a new top-level design for the selected job
:new_top_level_design_for	:en_gb	New Top-Level Design for #1...
:new_sub_design			:en_gb	New Sub-Design...
:new_sub_design_sh		:en_gb	Create a new sub-design for the selected design
:new_sub_design_for		:en_gb	New Sub-Design for #1...

:open_design			:en_gb	Open Design
:open_design_sh			:en_gb	Open the selected design
:open_design_for		:en_gb	Open Design #1
:close_design			:en_gb	Close Design
:close_design_sh		:en_gb	Close the design that is currently active
:merge_design			:en_gb	Merge Design
:merge_design_sh		:en_gb	Merge all datasets for the design that is currently active

:goto_selected_design		:en_gb	Goto Selected Design
:goto_selected_design_sh	:en_gb	Goto the selected design
:highlight_selected_design	:en_gb	Highlight Selected Design
:highlight_selected_design_sh	:en_gb	Highlight the selected design
:edit_selected_job		:en_gb	Edit Selected Job
:edit_selected_job_sh		:en_gb	Edit the selected job
:edit_selected_design		:en_gb	Edit Selected Design
:edit_selected_design_sh	:en_gb	Edit the selected design
:edit_active_job		:en_gb	Edit Active Job
:edit_active_job_sh		:en_gb	Edit the job that is currently active
:edit_active_design		:en_gb	Edit Active Design
:edit_active_design_sh		:en_gb	Edit the design that is currently active
:delete_selected_jobs		:en_gb	Delete Selected Jobs
:delete_selected_jobs_sh	:en_gb	Delete the selected jobs
:delete_selected_designs	:en_gb	Delete Selected Designs
:delete_selected_designs_sh	:en_gb	Delete the selected designs

:overlay_selected_design	:en_gb	Overlay Selected Design
:overlay_selected_design_sh	:en_gb	Dynamically overlay the selected design in the map window
:clear_overlay_design		:en_gb	Clear Overlay Design
:clear_overlay_design_by_name	:en_gb	Clear Overlay #1
:clear_overlay_design_sh	:en_gb	Turn off the overlay design in the map window
:copy_overlay_design_data	:en_gb	Copy Overlay Design Data...
:copy_overlay_design_data_sh	:en_gb	Activate a menu to copy overlay design data into the active design
:overlay_selected_design_n	:en_gb	Secondary Overlay #1
:overlay_selected_design_n_sh	:en_gb	Dynamically overlay the selected design in the map window
:clear_overlay_design_n		:en_gb	Clear Secondary Overlay #1
:clear_overlay_design_n_by_name	:en_gb	Clear Overlay #1: #2
:clear_overlay_design_n_sh	:en_gb	Turn off the overlay design in the map window

:aggregate_selected_designs	:en_gb	Aggregate Selected Designs
:aggregate_selected_designs_sh	:en_gb	Aggregate the selected designs into the active design

:confirm_merge_design		:en_gb
Confirm that design #1 should be merged.  This will refresh the design data with up-to-date information from the top alternative.
:confirm_delete_job		:en_gb	
Confirm that job #1 should be deleted.  Note that this will permanently delete any design data associated with all designs for this job.
:confirm_delete_jobs		:en_gb	
Confirm that the #1 selected jobs should be deleted.  Note that this will permanently delete any design data associated with all designs for these jobs.
:confirm_delete_design		:en_gb	
Confirm that design #1 should be deleted.  Note that this will permanently delete any design data associated with this design.
:confirm_delete_designs		:en_gb	
Confirm that the #1 selected designs should be deleted.  Note that this will permanently delete any design data associated with these designs.
:confirm_aggregate_design	:en_gb	
Confirm that design #1 should be aggregated into the active design.  Note that this will permanently change the contents of the active design.
:confirm_aggregate_designs	:en_gb	
Confirm that the #1 selected designs should be aggregated into the active design.  Note that this will permanently change the contents of the active design.

:opening_design			:en_gb	Opening design #1...
:deleting_records		:en_gb	Deleting records...
:overlaying_design		:en_gb	Overlaying design #1...
:clearing_overlay_design	:en_gb	Clearing overlay design...
:aggregating_design		:en_gb	Aggregating design #1 into active design #2...

:no_selected_job		:en_gb	No selected job.
:no_selected_design		:en_gb	No selected design.
:no_selected_jobs		:en_gb	No selected jobs.
:no_selected_designs		:en_gb	No selected designs.
:no_active_job			:en_gb	No active job.
:no_active_design		:en_gb	No active design.
:no_editor_manager		:en_gb	No editor manager is available to edit this record.
:cannot_delete_active_design	:en_gb	Cannot delete the active design - close this design before proceeding.
