#% text_encoding = iso8859_1

:class_count_info		#1 - ###2 method(s), #3 file(s)
:compress_all			Compress all
:compress_l2			Compress 2nd level
:count_hdr			## Methods
:data_hdr			Class / File(s) / Method(s)
:edit_file_command		#1 "#2"
:expand_all			Expand all
:expand_l2			Expand 2nd level
:export2html			Export to HTML
:export_completed		Data written to file '#1'.
:export_file_name		#1_rec_ex_files.html
:file_method_info		#t#1 (#2)
:gnuclient_cmd			gnuclientw -q
:gui_file_info			#s- #1 file
:gui_files_info			#s- #1 files
:method_name_info		#t#t#1
:refresh			Refresh
:remove_from_list		Remove Selected Items
:resize_columns			Adjust Column Widths
:sf!data_model_code_info	Record Exemplar Code Spread
:title				Dataset #1 - Record Exemplar Code Spread
:unset_file			- no source file info -