#% text_encoding = iso8859_1

:delete_alternatives		:en_gb	Delete Unused Alternatives

:delete_alternatives_start	:en_gb	#1: Start process.
:delete_alternatives_end	:en_gb	#1: End process: number of deleted alternatives = #2, errors during deletion = #3.
:determine_to_del_start		:en_gb	#1: Checking database #2, root alternative = #3.
:determine_to_del_end		:en_gb	#1: Done checking #2: number to be deleted = #3.
:removing_alternative		:en_gb	#1: Removing #3 from parent #2.
:removing_alternative_design	:en_gb	#1: Removing #3 from parent #2 (design = #4).
:cannot_delete_alternative	:en_gb	ERROR: cannot delete, because: #1
:something_changed		:en_gb	Data has changed since alternative was marked for deletion.
