#% text_encoding = iso8859_1

:delete_designs			:en_gb	Delete Completed/Cancelled Designs

:delete_design_count		:en_gb	Number of deleted designs: #1
:delete_job_count		:en_gb	Number of deleted jobs: #1
:deleting_design		:en_gb	Deleting design: #1 ...
:deleting_job			:en_gb	Deleting job: #1 ...
:delete_ok			:en_gb	OK
:delete_error			:en_gb	Error

:too_many_errors		:en_gb	Too many errors encountered - stopping process
