#% text_encoding = iso8859_1

:post_design			:en_gb	Post Design

:design_id			:en_gb	Design ID
:conflict_mode			:en_gb	Conflict Mode
:post_complete_state		:en_gb	Post Complete State
:post_fail_state		:en_gb	Post Fail State

:design_id_not_found		:en_gb	Design ID #1 not found
:complete_state_not_found	:en_gb	Post complete state #1 not found
:fail_state_not_found		:en_gb	Post fail state #1 not found
