#% text_encoding = iso8859_1

:design_state_transition	:en_gb	Design State Transition
:job_state_transition		:en_gb	Job State Transition

:design_id			:en_gb	Design ID
:job_id				:en_gb	Job ID
:from_state_name		:en_gb	From State Name
:to_state_name			:en_gb	To State Name

:design_id_not_found		:en_gb	Design ID #1 not found
:job_id_not_found		:en_gb	Job ID #1 not found
:wrong_from_state		:en_gb	#1 is in state #2, should be in state #3
:missing_transition		:en_gb	#1 has no state transition from #2 to #3
