:action		Action
:alpha		Alphabetic
:app		App

:category	种类
:colon		:
:common		公共的

:element_id_not_unique	其它的对话框元素已经使用了
dialog_element_id = '#1'

:filename	文件名称

:image		图像
:image_filtering	图像过滤 - 增量的

:module			模块

:no_app_running		没有活动的应用程序

:plugin			Plugin
:plugin_action_filtering	Plugin/Action 过滤
:product			产品
:property		属性

:refresh_app_list		刷新应用程序列表

:set_image_resource	设置图像的源 ... 
:set_large_image_resource	设置大图像的源 ...
:set_logical_values	设置'选择器'值
:set_plugin_resource	设置 plugin / action ...

:value			值

:window_id_not_unique	窗口名称 '#1' 在窗口堆栈中不唯一.

