#% text_encoding = iso8859_1

:insert_related_document		:en_gb	Insert Related Document Reference
:insert_related_document_sh		:en_gb	Insert a reference to a new related document
:update_selected_related_document	:en_gb	Update Selected Related Document Reference
:update_selected_related_document_sh	:en_gb  Update the selected related document reference
:delete_selected_related_document	:en_gb	Delete Selected Related Document Reference
:delete_selected_related_document_sh	:en_gb  Delete the selected related document reference
:display_selected_related_document	:en_gb	Display Selected Related Document
:display_selected_related_document_sh	:en_gb  Display the selected related document
:refresh_result_list			:en_gb	Refresh
:refresh_result_list_sh			:en_gb	Refresh list of related documents

:rch_full_filename			:en_gb	Filename
:rch_usage_string			:en_gb	Usage

:tab_label				:en_gb	Related Documents
:current_object_string			:en_gb	Related documents for #1
:current_object_string_none		:en_gb	No current object

:attribute_list_header			:en_gb	Attributes for inserting or updating a related document:
:ach_attribute_name			:en_gb	Attribute Name
:ach_attribute_value			:en_gb	Attribute Value
:attr_name_full_filename		:en_gb	Filename
:attr_name_usage_string			:en_gb	Usage
:attr_name_comments			:en_gb	Comments

:confirm_delete				:en_gb	Delete reference to related document #1?  Note that only removes the reference to the document, and the file itself is not deleted.
:no_full_filename			:en_gb	The filename must be entered.
:no_current_object			:en_gb	No current object.
:no_selected_related_document		:en_gb	No selected related document.
