:action				Action
:alpha				알파벳
:app				어플리케이션
:category			카테고리
:colon				:
:common				Common

:element_id_not_unique	이미 다른 다이알로그 엘리먼트가 dialog_element_id = '#1' 를 가지고 있슴니다.
:filename			파일이름
:image				이미지

:image_filtering		이미지 필터링 - Incremental
:module				모듈
:no_app_running			활성된 프로그램이 없슴니다
:plugin				Plugin
:plugin_action_filtering	Plugin/Action 필터링
:property			속성
:set_image_resource		이미지 설정 ... 

:set_plugin_resource		Plusin/Action 설정 
:value				값
:window_id_not_unique		윈도우 '#1'는 윈도우 스텍에 유일하지 않슴니다.
