#% text_encoding = iso8859_1

:process_tasks			:en_gb	Process Tasks
:process_tasks_sh		:en_gb	Process tasks that are scheduled to be run
:soft_interrupt			:en_gb	Soft Interrupt
:soft_interrupt_sh		:en_gb	Stop processing tasks after the current task is complete
:hard_interrupt			:en_gb	Hard Interrupt
:hard_interrupt_sh		:en_gb	Stop processing tasks immediately - interrupting the current task

:tab_label			:en_gb	Task Types
:ch_task_type			:en_gb	Task Type
:ch_enabled?			:en_gb	Enabled?

:warn_hard_interrupt		:en_gb	Warning: performing a hard interrupt will cause the task that is currently running to fail to complete properly.  Are you sure you want to perform a hard interrupt?
:interrupted			:en_gb	Interrupted
:waiting_for_task		:en_gb	Waiting for next task...
:performing_task		:en_gb	Performing task #1...

:dataset_open_failed		:en_gb	Unable to open datasets for mss_scheduler_engine database view.
:task_server_running		:en_gb	Cannot close while the task server is running.
:major_error			:en_gb	Major error encountered in outer loop of scheduler: traceback follows:
:major_error_count_exceeded	:en_gb	Too many major errors in outer loop of scheduler: processing stopped.
:warn_major_errors		:en_gb	Warning: #1 major error(s) encountered - see session log for details.
:fail_no_handler		:en_gb	No handler for task
:fail_hard_interrupt		:en_gb	Hard Interrupt
:fail_unknown_reason		:en_gb	Unknown failure
