#% text_encoding = iso8859_1

:merge				:en_gb	Merge Alternative
:merge_and_post			:en_gb	Merge and Post Alternative
:merge_all_children		:en_gb	Merge All Child Alternatives
:merge_and_post_from_file	:en_gb	Merge and Post From File

:partition_name			:en_gb	Partition Name
:alternative_name		:en_gb	Alternative Name
:conflict_mode			:en_gb	Conflict Mode
:input_file			:en_gb	Input File

:starting_process		:en_gb	#1 Starting process
:starting_process_multi		:en_gb	#1 Starting process (#2 operations to be done)
:process_complete		:en_gb	#1 Process complete 
:process_complete_errors	:en_gb	#1 Process complete, but with errors
:starting_operation		:en_gb	#1 Operation #2: Starting #3 on #4,#5

:error_reported			:en_gb	Error reported performing this operation - see error log
:generic_vmds_error		:en_gb	#1 Error performing #2 on #3,#4
:conflicts_not_handled		:en_gb	Conflicts not handled
:unknown_error_during_post	:en_gb	Unknown error while posting alternative
:unknown_type			:en_gb	Unknown task type: #1
