#% text_encoding = iso8859_1

:clear_proposed_changes		:en_gb	Clear Proposed Changes
:clear_proposed_changes_sh	:en_gb	Resets proposed changes back to original values
:perform_update			:en_gb	Bulk Update
:perform_update_sh		:en_gb	Perform bulk update for selected tables
:perform_delete			:en_gb	Bulk Delete
:perform_delete_sh		:en_gb	Perform bulk delete for selected tables
:interrupt			:en_gb	Interrupt
:interrupt_sh			:en_gb	Interrupt a background add, goto, or highlight operation
:add_by_map_selection		:en_gb	Add by Map Selection
:add_by_map_selection_sh	:en_gb	Add objects based on current map selection
:add_by_trail			:en_gb	Add by Trail
:add_by_trail_sh		:en_gb	Add objects based on selectable data inside the current trail
:add_by_scrapbook		:en_gb	Add by Scrapbook
:add_by_scrapbook_sh		:en_gb	Add records from the scrapbook
:remove_by_map_selection	:en_gb	Remove by Map Selection
:remove_by_map_selection_sh	:en_gb	Remove objects based on current map selection
:remove_object			:en_gb	Remove Current Record
:remove_object_sh		:en_gb	Remove the selected record from the bulk update process
:remove_selected_tables		:en_gb	Remove Selected Tables
:remove_selected_tables_sh	:en_gb	Remove all records in the selected tables from the bulk update process
:remove_all			:en_gb	Remove All
:remove_all_sh			:en_gb	Remove all records from the bulk update process
:remove_by_attribute		:en_gb	Remove by Attribute...
:remove_by_attribute_sh		:en_gb	Remove records based on a specified attribute value
:edit_object			:en_gb	Edit Current Record...
:edit_object_sh			:en_gb	Display the editor for the selected record
:copy_to_scrapbook		:en_gb	Copy to Scrapbook
:copy_to_scrapbook_sh		:en_gb	Copy all records in the selected tables to the scrapbook
:goto_object			:en_gb	Goto Current Record
:goto_object_sh			:en_gb	Goto the selected record
:goto_selected_tables		:en_gb	Goto Selected Tables
:goto_selected_tables_sh	:en_gb	Goto all records in the selected tables
:goto_all			:en_gb	Goto All
:goto_all_sh			:en_gb	Goto all records
:highlight_object		:en_gb	Highlight Current Record
:highlight_object_sh		:en_gb	Highlight the selected record
:highlight_selected_tables	:en_gb	Highlight Selected Tables
:highlight_selected_tables_sh	:en_gb	Highlight all records in the selected tables
:highlight_all			:en_gb	Highlight All
:highlight_all_sh		:en_gb	Highlight all records
:display_first			:en_gb	Display First
:display_first_sh		:en_gb	Display first record in the selected table
:display_next			:en_gb	Display Next
:display_next_sh		:en_gb	Display next record in the selected table
:display_last			:en_gb	Display Last
:display_last_sh		:en_gb	Display last record in the selected table
:display_prev			:en_gb	Display Previous
:display_prev_sh		:en_gb	Display previous record in the selected table
:suppress_warnings?		:en_gb	Suppress Warnings?
:suppress_warnings?_sh		:en_gb	Prevent warning messages from displaying an alert dialog
:force_commit?			:en_gb	Require Commit Before Running?
:force_commit?_sh		:en_gb	If selected, you cannot perform a bulk update with uncommitted changes
:append_text_joins?		:en_gb	Append To Text Joins?
:append_text_joins?_sh		:en_gb	If selected, values for text join fields will be appended, rather than updated
:ch_rec_number			:en_gb	Record
:ch_rec_count			:en_gb	Count
:ch_table_name			:en_gb	Table Name
:rec_of				:en_gb	#1 of
:current_record_count		:en_gb	Current records: #2 in #1 table(s)
:bulk_update_scrapbook		:en_gb	Bulk Update Scrapbook
:copied_to_scrapbook		:en_gb	Selected tables copied to scrapbook.
:do_bulk_update			:en_gb	Bulk Update
:progress_bulk_update		:en_gb	Doing Bulk Update - #2 of #1 records processed...
:done_bulk_update		:en_gb	Done Bulk Update - #2 of #1 records changed.
:confirm_bulk_delete		:en_gb	Are you sure you wish to delete all selected records?
:do_bulk_delete			:en_gb	Bulk Delete
:progress_bulk_delete		:en_gb	Doing Bulk Delete - #2 of #1 records processed...
:done_bulk_delete		:en_gb	Done Bulk Delete - #1 records deleted.

:interrupted			:en_gb	Interrupted.
:bad_trail			:en_gb	The trail must form an area.
:no_current_record		:en_gb	Select a table and record before performing this function.
:no_collection			:en_gb	Select a table before performing this function.
:no_selected_tables		:en_gb	Select one or more tables before performing this function.
:no_data_available		:en_gb	No data available - add records before performing this function.
:no_proposed_changes		:en_gb	Make proposed changes to one or more fields before performing the bulk update.
:not_writable			:en_gb	The #1 database is not writable.
:not_write_authorised		:en_gb	You do not have permission to update the #1 table.
:db_updated			:en_gb	The #1 database has been updated - commit or rollback before proceeding.
:select_single_field		:en_gb	Select a single field before performing this function.
:failed_on_record		:en_gb	Failed on record #1 of #2: #3
