#% text_encoding = iso8859_1

:duplicate_internal_name	:en_gb	A workflow with internal name #1 already exists.
:duplicate_name			:en_gb	A workflow with name #1 already exists.
:duplicate_state		:en_gb	A state named #1 already exists in this workflow.
:duplicate_state_transition	:en_gb	A state transition for #1, #2, #3 already exists in this workflow.
:missing_state			:en_gb	No state named #1.
:no_initial_state		:en_gb	No initial state defined for record type #1.
