#% text_encoding = iso8859_1

:duplicate_name			:en_gb	A job named #1 already exists.
:auth_job_delete_error		:en_gb	You do not have sufficient authorisation to delete all designs for job #1.
:insert_no_initiator		:en_gb	Use workspace manager functions to insert a new job.
:update_status_no_initiator	:en_gb	Use workspace manager functions to change the status of a job.
:delete_no_initiator		:en_gb	Use workspace manager functions to delete a job.
:incompatible_job_types		:en_gb	Changing the type for #1 from #2 to #3 requires the use of different datasets for your designs.  Contact your administrator for assistance in performing this update.
:incompatible_workflows		:en_gb	Changing the type for #1 from #2 to #3 requires the use of different workflows.  In order to do this, the job and all of its designs must be in the initial state.  Contact your administrator for assistance in performing this update.
:no_job_type_for_record		:en_gb	No job type is available for #1.  Contact your administrator to correct your workflow configuration.
:no_workflow_for_record		:en_gb	No workflow is available for #1.  Contact your administrator to correct your workflow configuration.
:no_state_for_record		:en_gb	No state is available for #1.  Contact your administrator to correct your workflow configuration.
:cannot_delete_for_state	:en_gb	#1: a job with a status of #2 cannot be deleted.
