#% text_encoding = iso8859_1

:first_design_name		:en_gb	1

:duplicate_name			:en_gb	A design named #2 already exists for job #1.
:insert_no_initiator		:en_gb	Use workspace manager functions to insert a new design.
:update_status_no_initiator	:en_gb	Use workspace manager functions to change the status of a design.
:delete_no_initiator		:en_gb	Use workspace manager functions to delete a design.
:cannot_delete_subdesigns	:en_gb	Design #1 cannot be deleted, as it has sub-designs.
:not_active_design		:en_gb	Design #1 must be open to perform this operation.
:auth_design_change_owner_error	:en_gb	You do not have sufficient authorisation to update the owner of #1 from #2 to #3.
:auth_design_delete_error	:en_gb	You do not have sufficient authorisation to delete design #1.
:no_job_type_for_record		:en_gb	No job type is available for #1.  Contact your administrator to correct your workflow configuration.
:no_workflow_for_record		:en_gb	No workflow is available for #1.  Contact your administrator to correct your workflow configuration.
:no_state_for_record		:en_gb	No state is available for #1.  Contact your administrator to correct your workflow configuration.
:already_singular_design	:en_gb	Cannot change status of #1 to #2, because #3 already has a status of #4.  Only one design is allowed with any of these status values for this job.
:cannot_delete_for_state	:en_gb	#1: a design with a status of #2 cannot be deleted.
:overlay_copy_from_not_allowed	:en_gb	Copying data from an overlay design in the #2 state (#3) to the active design in the #1 state is not allowed.
:aggregate_from_not_allowed	:en_gb	Aggregating data from design #4 in the #2 state (#3) to the active design in the #1 state is not allowed.
:self_aggregate_not_allowed	:en_gb	The design #1 cannot be aggregated into itself.
:pc_aggregate_not_allowed	:en_gb	The design #1 is a parent of #2, and so they cannot be aggregated.
