:action		Action
:alpha		Alphabetic
:app		App

:category	Category
:colon		:
:common		Common

:element_id_not_unique	Some other dialog element already has 
dialog_element_id = '#1'

:filename	Filename

:image		Image
:image_filtering	Image Filtering - Incremental

:module			Module

:no_app_running		No active Applications

:plugin			Plugin
:plugin_action_filtering	Plugin/Action Filtering
:product			Product
:property		Property

:refresh_app_list		Refresh Application List

:set_image_resource	Set image source ... 
:set_large_image_resource	Set LARGE image source ...
:set_logical_values	Set 'Selector' values
:set_plugin_resource	Set plugin / action ...

:value			Value

:window_id_not_unique	The window_name '#1' is not unique to this window stack.

