#% text_encoding = iso8859_1

:set_chain_from_trail		:en_gb	Set Construction From Trail
:set_chain_from_selection	:en_gb	Set Construction From Selection

:tab_label			:en_gb	Construction
:extend_distance		:en_gb	Extend distance:
:use_centerline?		:en_gb	Use centerline?	
:offset_distance		:en_gb	Offset distance:
:use_offset?			:en_gb	Use offset?
:dynamic_mode			:en_gb	Dynamic mode:
:use_dynamic?			:en_gb	Use dynamic?

:no_construction_manager	:en_gb	No construction manager plugin found for this application.  Construction features have been disabled.
:no_trail_for_chain		:en_gb	A multi-point trail is required to create a chain construction line.
