:action		Acción
:alpha		Alfabético 
:app		App

:category	Categoría 
:colon		:
:common		Común 

:element_id_not_unique	Algún otro elemento del diálogo ya utiliza  
dialog_element_id = '#1'

:filename	Nombre del fichero

:image		Imagen 
:image_filtering	Filtro de imagen - Incremental

:module			Módulo

:no_app_running		Ninguna aplicación activa

:plugin			Plugin
:plugin_action_filtering	Filtro Plugin/Action
:product			Producto
:property	Propiedad

:refresh_app_list		Refrescar Lista de Aplicaciones

:set_image_resource	Seleccionar imagen ... 
:set_large_image_resource	Selecciona  imagen (large) ...
:set_logical_values	Añadir 'Selector' de valores
:set_plugin_resource	Seleccionar plugin / action ...

:value		Valor 

:window_id_not_unique	El window_name '# 1' no es único para esta pila de ventanas (Window Stack).

