#% text_encoding = iso8859_1

:tab_label			:en_gb	CU Report
:refresh			:en_gb	Refresh
:export_to_excel		:en_gb	Export to Excel
:combine_similar_cus?		:en_gb	Combine Similar CUs?
:include_cus_with_no_operation?	:en_gb	Include CUs With No Operation Value?
:include_parent_designs?	:en_gb	Include Parent Designs?
:work_point_subtotals?		:en_gb	Work Point Subtotals?

:current_cu_cost_group		:en_gb	Cost group:
:default_cu_cost_group		:en_gb	(Default costs)
:default_cu_cost_group_report	:en_gb	default costs

:report_summary			:en_gb	Summary:
:work_point_summary		:en_gb	Work point subtotal:

:excel_sheet_name		:en_gb	CU Report
:header_line_1			:en_gb	CU report for #1
:header_line_2			:en_gb	Created on #1
:header_line_3			:en_gb	Cost group: #1

:calculating_cus		:en_gb	Calculating CUs...
:displaying_results		:en_gb	Displaying results...
:exporting_to_excel		:en_gb	Exporting to Excel...

:warn_edit_cu_reference		:en_gb	This is a CU for a facility that has been deleted.  Therefore, the CU data will be edited directly.
:confirm_overwrite		:en_gb	File #1 already exists - OK to overwrite?
:cannot_create_file		:en_gb	Cannot create file #1 - please save the resulting spreadsheet to a different file.
:no_active_design		:en_gb	No active design - cannot create CU report.
:cannot_edit_aggregator		:en_gb	This is a combined record, which represents multiple individual CUs.  To edit an individual CU, either expand this selection and choose the desired CU, or deselect the 'Combined Similar CUs' option.
:cannot_start_excel		:en_gb	Cannot start Microsoft Excel.  Please verify that it is installed on this computer.
:excel_could_not_get_access	:en_gb
The CU reporter could not get access to Microsoft Excel since it is currently busy.
Please close any windows that are currently open in Microsoft Excel.
