#% text_encoding = iso8859_1

:tab_label			:en_gb	Work Points
:assignment_mode		:en_gb	Assignment Mode:
:mode_assign_blank_wps		:en_gb	Assign work point values to CUs with blank work points
:mode_clear_wps			:en_gb	Clear work point values for CUs
:auto_refresh			:en_gb	Auto-refresh CU list after update?
:inside_trail			:en_gb	Limit search to CUs found inside the trail?
:perform_updates		:en_gb	Perform Updates

:performing_updates		:en_gb	Performing updates...
:refreshing_cu_list		:en_gb	Refreshing CU list...

:no_trail			:en_gb	A trail must be placed to define the extent of the search.
:incomplete_trail		:en_gb	The trail must define a closed area for the extent of the search.
:no_cus_to_do_assign_blank_wps	:en_gb	No CUs with blank work point values found - no updates to perform.
:no_cus_to_do_clear_wps		:en_gb	No CUs work non-blank work point values found - no updates to perform.
:no_cus_to_do			:en_gb	No CUs found - no updates to perform.
:database_not_writable		:en_gb	The #1 database is not writable.
:wps_updated_status		:en_gb	Updates done: #1 CUs examined, #2 CUs updated.
