#% text_encoding = iso8859_1

:float_conversion_error		:en_gb	Float conversion error: #1, #2
:stored_unit_conversion_error	:en_gb	Stored unit conversion error: #1, #2
:unexpected_error_maintaining_cus	:en_gb	An unexpected error has occurred while maintaing CUs: #1 should not exist.  Please contact your system administrator.
:no_matching_world_for_wp	:en_gb	No world exists in the #1 database in which work points can be created.
:straight_sector_required	:en_gb	Only straight sectors are allowed - no arcs or splines.
