:action	Action

:alpha		Alphabétique 
:app	App
:category	Catégorie 
:colon		:
:common		Commune

:element_id_not_unique	D'autres élément de dialogue a déjà
Dialog_element_id = '# 1' 
:filename	Nom de fichier
:image		Image

:image_filtering	Image Filtering - Incremental
:module		Module
:no_app_running		Applications non actif
:plugin	Plugin
:plugin_action_filtering	Plugin/Action Filtrage
:property	Attribut
:set_image_resource	Source de l'image ...  

:set_logical_values	Set 'Selector' valeurs
:set_plugin_resource	Define plugin / action 
:value		Valeur
:window_id_not_unique	La window_name '# 1' n'est pas unique à cette fenêtre pile.

