#% text_encoding = cp1252


:start_insync_mapping_editor_caption 	Insync Mapping
:start_insync_mapping_editor_comment 	Start the Insync Mapping editor

:start_basic_replication_editor_caption	Replication Editor
:start_basic_replication_editor_comment	Start the Replication Editor

:launch_thread_manager_caption		Thread manager
:launch_thread_manager_comment		Start the thread manager...

:launch_case_dump_dialog_caption	Case Reporter
:launch_case_dump_dialog_comment	Case HTML Report generator...

:launch_case_caption			Case Tool...
:launch_case_comment			Start the CASE tool...