#% text_encoding = iso8859_1

:prnt_file_name		#1_index_info.txt
:prnt_html_name		#1_index_info.htm
:prnt_csv_name		#1_index_info.csv
:prnt_table_info	#1#t#2#tRecords: #3#tPrimary table: #4 block(s).
:prnt_index_info	#s#s#s#sIndex size on disk: #1 block(s)
:prnt_index_fld_info	#t#1#t#2#t#3
:prnt_sep_line		#t============================================================
:list_sep_string	,#s
:gui_frame_title	Index Information for Dataset '#1' (#2)
:gui_all_tables?	Tables w/o add. indexes?
:gui_tbl_filter		Name Filter:
:gui_update		Refresh
:gui_header_col1	Records
:gui_header_col2	Internal Table Name
:gui_header_col3	External Table Name
:gui_header_col4	Total Blocks
:gui_header_col5	Data Blocks
:gui_header_col6	Index Blocks
:gui_idx_info		Index ###1

:gui_print_complete	Printed data to file '#1'.

:sf!html_title		Index Analysis for Dataset #1 [#2]