#% text_encoding = iso8859_1

:mss_ptrule_options_menu	Assistenten Optionen
:close				Schließen

:placement_mode_tab_label	Setzen
:placement_mode			Setzen-Modus:
:pm_design			Design
:pm_data_maintenance		Fortführung

:offset_tab_label		Offset
:offset_distance		Offset Abstand
:offset_direction		Offset Richtung:
:offset_direction_left		links
:offset_direction_right		rechts

:move_tab_label			Verschieben
:move_disconnect_before_transform?	Andere Geometrien trennen vor dem Verschieben eines Punktes?
