#% text_encoding = iso8859_1

:refresh			Assistentenliste neu laden
:activate_options_dialog	Optionen...

:missing_root_folder		Es ist kein Wurzelverzeichnis für verfügbare Assistenten konfiguriert.
:no_ptrule_manager		Es ist kein Assitenten-Manager (ptrule_manager) für diese Aktivität konfiguriert.

:no_active_pointing_rule	Kein Assistent aktiviert
:active_pointing_rule		Aktiver Assistent: #1
:no_match_by_name		Kein passender Eintrag gefunden zu: "#1"
