#% text_encoding = iso8859_1

:tab_label		:en_gb	Folders

:cut			:en_gb	Cut
:copy			:en_gb	Copy
:paste			:en_gb	Paste
:refresh		:en_gb	Refresh

:delete_folder			:en_gb	Delete
:new_root_folder		:en_gb	New Root Folder...
:new_sub_folder			:en_gb	New Sub Folder...
:folder_properties		:en_gb	Properties...
:export_selected_folder		:en_gb	Export Folder...

:contents_properties		:en_gb	Properties...
:delete_contents_relationship	:en_gb	Remove from Folder
:add_to_contents		:en_gb	Add to Folder
:edit_pointing_rule		:en_gb	Edit Selected Pointing Rule Definition...
:clone_pointing_rule		:en_gb	Clone Selected Pointing Rule Definition
:import_pointing_rules		:en_gb	Import Pointing Rule Definitions...
:import_preserve_folders?	:en_gb	Import: Preserve Folders?
:import_strict_folders?		:en_gb	Import: Strictly Retain Folder Structure?
:export_selected_ptrules	:en_gb	Export Selected Pointing Rule Definitions...
:filter				:en_gb	Filter

:confirm_delete			:en_gb	Are you sure you want to delete folder #1?
:cut_pending			:en_gb	Cut pending: #1
:cut_pending_multiple		:en_gb	Cut pending: #1 elements
:copy_pending			:en_gb	Copy pending: #1
:copy_pending_multiple		:en_gb	Copy pending: #1 elements

:undo_create_new_root_folder	:en_gb	Create new root folder #1
:undo_create_new_sub_folder	:en_gb	Create new sub folder #1
:undo_delete_folder		:en_gb	Delete folder #1
:undo_folder_properties		:en_gb	Update folder properties for #1
:undo_cut_and_paste		:en_gb	Cut and paste
:undo_copy_and_paste		:en_gb	Copy and paste
:undo_delete_contents_relationship	:en_gb	Remove from folder
:undo_add_to_contents		:en_gb	Add to folder
:undo_clone_pointing_rule	:en_gb	Clone pointing rule

:select_parent_folder		:en_gb	Select a parent folder for this operation.
:select_folder			:en_gb	Select a folder for this operation.
:select_ptdef			:en_gb	Select a pointing rule definition for this operation.
:select_data_for_cut		:en_gb	Select data for cut operation.
:select_data_for_copy		:en_gb	Select data for copy operation.
:select_ptdefs_to_remove	:en_gb	Select pointing rule definitions to remove.
:select_ptdefs_to_add		:en_gb	Select pointing rule definitions to add.
:import_dialog_title		:en_gb	Import Pointing Rule Definitions
:export_folder_dialog_title	:en_gb	Export Selected Folder
:export_ptrules_dialog_title	:en_gb	Export Selected Pointing Rule Definitions

:xml_filter			:en_gb	XML files (*.xml)
:xml_filetype			:en_gb	.xml

:dbv_updated			:en_gb	Database is updated - commit or rollback before performing this function.
:file_not_readable		:en_gb	File #1 cannot be read.
:file_not_writable		:en_gb	File #1 cannot be created.
:import_cannot_read_version	:en_gb	Import file version mismatch: version #1 found in file, but it should be version 1.
