#:show_multi_merge_scheme		Multi-Merge Jobs
#:show_multi_merge_scheme_sh	Show the Multi-Merge Jobs?
#:show_multi_merge_scheme_tt	Show the Multi-Merge Jobs?
:display_job_group				Display Jobs from:
:display_job_group_sh			Only Display Jobs from the selected group
:display_job_group_tt			Only Display Jobs from the selected group
:display_available_status		Display Jobs with Status:
:display_available_status_sh	Only Display Status with the selected status
:display_available_status_tt	Only Display Jobs with the selected status
:push_to_explorer				Export Selected Jobs to Explorer
:push_to_explorer_sh			Export Selected Jobs to Explorer
:push_to_explorer_tt			Export Selected Jobs to Explorer
:push_all_to_explorer			Export All Listed Jobs to Explorer
:push_all_to_explorer_sh		Export All Listed Jobs to Explorer
:push_all_to_explorer_tt		Export All Listed Jobs to Explorer
:display_list_count				Show the Displayed List Count
:display_list_count_sh			Show the Displayed List Count
:display_list_count_tt			Show the Displayed List Count
:displayed_jobs_not_counted		Displayed: Not Counted
:explorer_selected_jobs			Selected Jobs
:edit_object					Edit Selected Job
:edit_object_sh					Edit Selected Job
:edit_object_tt					Edit Selected Job
:filter_by_start_date			Filter by Start Date?
:filter_by_start_date_sh		Filter by Start Date?
:filter_by_start_date_tt		Filter by Start Date?
:displayed_jobs					Displayed: #1
:after_date_filter				Jobs Started After #1
:before_date_filter				Jobs Started Before #1
:no_filter_date					No Date Filtering
:cannot_remove_running_jobs	    You cannot remove a Job in a "Running" status
:find_default_text_id			Search Text
:no_categories					No Categories
:display_text_input             Search Text
:display_text_input_tt	        Insert text for searching
:display_text_input_sh          Insert text for searching
:display_text_field             Search Field
:display_text_field_tt          Select field to search
:display_text_field_sh	        Select field to search
:all_jobs						All Jobs
:null_group						Null Group

