#% text_encoding = iso8859_1

:title_no_selected_job		:en_gb	(No Selected Job)
:title_selected_job		:en_gb	Job #1
:title_no_selected_design	:en_gb	(No Selected Design)
:title_selected_design		:en_gb	Design #1
:title_no_active_design		:en_gb	(No Active Design)
:title_active_design		:en_gb	Design #1
:no_subsequent_states		:en_gb	(No Subsequent States)

:performing_state_transition	:en_gb	Moving from #1 to #2 for #3...
:invalid_design			:en_gb	The selected design has been deleted.
