:action	Acção 

:alpha		Alfabético
:app	App
:category	Category
:colon		:
:common		Comum

:element_id_not_unique	Alguns outros diálogo elemento já possui
dialog_element_id = '#1'
:filename	Filename
:image		Imagem

:image_filtering	Image Filtering - Incremental
:module		Módulo 
:no_app_running		No activa Applications 
:plugin	Plugin
:plugin_action_filtering	Plugin / Action Filtering 
:property	Propriedade 
:set_image_resource	Set imagem fonte ...

:set_logical_values	Set 'Selector' valores
:set_plugin_resource	Set plugins / acção 
:value		Value
:window_id_not_unique	O window_name '# 1' não é exclusivo para esta janela pilha.


