:action		Action
:alpha		Alfabetico
:app		App

:category	Categoria
:colon		:
:common		Common

:element_id_not_unique	Un altro elemento ha già il
dialog_element_id = '#1'

:filename	Nome del File

:image		Immagine
:image_filtering	Ricerca Immagine - Incrementale

:module			Modulo

:no_app_running		Nessuna Applicazione attiva

:plugin			Plugin
:plugin_action_filtering	Ricerca Plugin/Action 
:product			Prodotto
:property		Proprietà

:refresh_app_list		Aggiorna la lista delle Applicazioni

:set_image_resource	Scegli immagine ... 
:set_large_image_resource	Scegli immagine GRANDE...
:set_logical_values	Scegli il valore del 'Selector' 
:set_plugin_resource	Scegli plugin / action ...

:value			Valore

:window_id_not_unique	Il nome della finestra '#1' non è univoco in questo stack.

