#% text_encoding = iso8859_1

:mss_job_history_viewer	:en_gb	Job History

:rch_action		:en_gb	Action
:rch_name		:en_gb	Name
:rch_type		:en_gb	Type
:rch_status		:en_gb	Status
:rch_last_update_user	:en_gb	Updated By
:rch_last_update_time	:en_gb	Update Time

:action_insert		:en_gb	Insert
:action_update		:en_gb	Update
:action_delete		:en_gb	Delete

:no_current_object	:en_gb	No current record
:current_object_string	:en_gb	History for #1:
