:action					Åtgärd
:alpha					Alfabetiskt
:app					App

:category				Kategori
:colon					:
:common					Gemensamma

:element_id_not_unique			Annan dialogruta element har redan
dialog_element_id = '#1'

:filename				Filnamn

:image					Bild
:image_filtering			Bild Filtering - stegvis

:module			    		 Modul

:no_app_running				Inga aktiva program

:plugin			     	    	Plugin
:plugin_action_filtering	    	Plugin/Åtgärds filtrering
:product			    	Produkt
:property			    	Egenskap

:refresh_app_list		    	Uppdatera program lista

:set_image_resource		    	Ange bild källa... 
:set_large_image_resource	    	Ange STOR bild källa...
:set_logical_values		    	Ange 'Valda' värden
:set_plugin_resource		    	Set plugin / åtgärd ...

:value				    	Värde

:window_id_not_unique		     	Fönsternamnet '#1' måste vara unikt

